name: ADDRESS EXE
on: [push]  
jobs:
   build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: ADDRESS EXE
      run: |
         msbuild -version
         dir project\main
         cd project\main
         g++ -o address2024test address2024test.cpp
         .\address2024test.exe > print.txt
         type print.txt
      shell: cmd
