name: ADDRESS EXE
on: [push]  
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: ADDRESS EXE
      run: |
         dir project/main
         cd project/main
         g++ -o address2024-test address2024-test.cpp
         ./address2024-test > input-address.txt
         cat input-address.txt
#      shell: cmd
    - name: Upload outline
      uses: actions/upload-artifact@v4
      with:
        name: input-address
        path: project/main/input-address.txt
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Download output
      uses: actions/download-artifact@v4
      with:
        name: input-address
        path: project/main/input-address.txt
    - name: Run another C++ code
      run: |
         dir project/main
         cd project/main
         g++ -o address2024test-in address2024test-in.cpp
         ./address2024test-in < input-address.txt > output-address.txt
         cat output-address.txt
#      shell: cmd
    - name: Upload output
      uses: actions/upload-artifact@v4
      with:
        name: output-address
        path: project/main/output-address.txt
    - name: output-address
      run: |
         dir project/main
         cd project/main
         cat output-address.txt
#      shell: cmd
  job3:
    needs: job2
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Download input
      uses: actions/download-artifact@v4
      with:
        name: input-address
        path: project/main/input-address.txt
    - name: Upload output
      uses: actions/upload-artifact@v4
      with:
        name: output-address
        path: projectmain/output-address.txt
         - name: Checkout code
        uses: actions/checkout@v3
      - name: Install diffutils
        run: sudo apt-get install diffutils
      - name: Compare files
        run: |
        dir project/main
        cd project/main
        diff project/main/input-address.txt project/main/output-address.txt > diff_output.txt
          if [ -s diff_output.txt ]; then
            echo "Differences found:"
            cat diff_output.txt
          else
            echo "No differences found."
          fi
