name: ADDRESS EXE
on: [push]  
jobs:
  job1:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: ADDRESS EXE
      run: |
         msbuild -version
         dir project\main
         cd project\main
         g++ -o address2024-test address2024-test.cpp
         .\address2024-test.exe > input-address.txt
         type input-address.txt
      shell: cmd
    - name: Upload outline
      uses: actions/upload-artifact@v4
      with:
        name: input-address
        path: project\main\input-address.txt
  job2:
    needs: job1
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Download output
      uses: actions/download-artifact@v4
      with:
        name: input-address
        path: project\main\input-address.txt
    - name: Run another C++ code
      run: |
         dir project\main
         cd project\main
         g++ -o address2024test-in address2024test-in.cpp
         .\address2024test-in.exe input-address.txt > output-address.txt
         type output-address.txt
      shell: cmd
    - name: Upload output
      uses: actions/upload-artifact@v4
      with:
        name: output-address
        path: project\main\output-address.txt
    - name: output-address
      run: |
         dir project\main
         cd project\main
         type output-address.txt
      shell: cmd
  job3:
    needs: job2
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Download output
      uses: actions/download-artifact@v4
      with:
       name: input-address
       path: project\main\input-address.txt
    - name: Upload output
      uses: actions/upload-artifact@v4
      with:
       name: output-address
       path: project\main\output-address.txt
    - name: Compare two text files
      run: |
        file1 = 'project\main\input-address.txt'
        file2 = 'project\main\output-address.txt'
        diff = ("file1") ("file2")
        if (diff) {
            Write-Output "Differences found:"
            Write-Output diff
        } else {
            Write-Output "No differences found."
        }
      shell: pwsh
