name: ADDRESS EXE
on: [push]  
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: ADDRESS EXE
      run: |
         dir project/main
         cd project/main
         g++ -o address2024-test address2024-test.cpp
         ./address2024-test > address.txt
         cat address.txt
#      shell: cmd
    - name: Upload outline
      uses: actions/upload-artifact@v4
      with:
        name: address.txt
        path: project/main/address.txt
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Download output
      uses: actions/download-artifact@v4
      with:
        name: address.txt
        path: project/main/address.txt
    - name: Run another C++ code
      run: |
         ls project/main
         cd project/main
         g++ -o address2024test-in address2024test-in.cpp
         ./address2024test-in < address.txt > output-address.txt
    - name: Show output
      run: cat output.txt
 #     shell: cmd
    - name: Upload output
      uses: actions/upload-artifact@v4
      with:
        name: output-address.txt
        path: project/main/output-address.txt
    - name: output-address
      run: |
         ls project/main
         cat project/main/output-address.txt
  #    shell: cmd
  job3:
    needs:  [job1, job2]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Download outline
      uses: actions/download-artifact@v4
      with:
         name: address.txt
         path: project/main
    - name: Download output
      uses: actions/download-artifact@v4
      with:
        name: output-address.txt
        path: project/main
    - name: Compare files
      run: |
         ls project/main
         ls -l project/main
         cd project/main
         cat address.txt
         diff -c project/main/address.txt project/main/output-address.txt
#        cd project/main/
#        ls output-address.txt
#        cat project/main/output-address.txt/output-address.txt
#        diff input-address.txt output-address.txt
#          if [ -s diff_output.txt ]; then
#            echo "Differences found:"
#            cat diff_output.txt
#          else
#            echo "No differences found."
