name: Share data between jobs with C++
on: [push]
jobs:
  job1:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Run C++ code
      run: |
        dir project\main
        cd project\main
        g++ -o main-test.exe main-test.cpp
        .\main-test.exe > outline.txt
      shell: cmd
    - name: Upload output
      uses: actions/upload-artifact@v4
      with:
        name: outline
        path: project\main\outline.txt

  job2:
    needs: job1
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Download outline
      uses: actions/download-artifact@v4
      with:
        name: outline
        path: project\main\outline.txt
    - name: Run another C++ code
      run: |
         dir project\main
         cd project\main
         g++ -o test_20240520 test_20240520.cpp
         .\test_20240520.exe outline.txt > test.txt
      shell: cmd
    - name: Upload output
      uses: actions/upload-artifact@v4
      with:
        name: test
        path: project\main\test.txt

  job_3:
    name: job 3
    needs: job2
    runs-on: ubuntu-latest
    steps:
    - name: Download test
      uses: actions/download-artifact@v4
      with:
        name: test
        path: project\main\test.txt
    - name: Run another C++ code
      run: |
          dir project\main
          cd project\main
          test.txt
      shell: cmd
