name: Run EXE
on: [push]  
jobs:
   build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run1 EXE
      run: |
         msbuild -version
         dir project\main
         cd project\main
         g++ -o main-test main-test.cpp
         main-test.exe
      shell: cmd
