name: Share data between jobs with C++1
on: [push]
jobs:
runs-on: windows-latest
    steps:
      uses: actions/checkout@v4
    - name: Run another C++ code
      run: |
         dir project\main
         cd project\main
         g++ -o Untitled-1 Untitled-1.cpp 
         .\Untitled-1.exe >output.txt
      shell: cmd
