name: Share data between jobs with C++1
on: [push]
jobs:
 job2:
    needs: job1
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Download output
      uses: actions/download-artifact@v4
    - name: Run another C++ code
      run: |
         dir project\main
         cd project\main
         g++ -o Untitled-1 Untitled-1.cpp 
         .\Untitled-1.exe >output.txt
      shell: cmd
