name: Run EXE
on: [push]  
jobs:
   build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run1 EXE
      run: |
         dir project\main
         cd project\main
         g++ -o Untitled-1 Untitled-1.cpp
         .\Untitled-1.exe
      shell: cmd
